// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MyComponent from "../../../my-components/src/myComponent.bs.mjs";
import * as AppModuleCss from "./app.module.css";

var styles = AppModuleCss;

function App(props) {
  return React.createElement("div", undefined, React.createElement(MyComponent.make, {}));
}

var make = App;

export {
  styles ,
  make ,
}
/* styles Not a pure module */
