// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MyComponentsModuleCss from "./my-components.module.css";

var styles = MyComponentsModuleCss;

function MyComponent(props) {
  return React.createElement("div", {
              className: styles.container
            }, React.createElement("h1", undefined, "Welcome to MyComponents!"));
}

var make = MyComponent;

export {
  styles ,
  make ,
}
/* styles Not a pure module */
